model:
  lr: .1
  num_epochs: 75
data:
  test_size: .2
  batch_size: 128
  num_ratings_thresh: 20
metrics:
  num_train_examples_until_record_metrics: 1000 
  num_test_examples_until_record_metrics: 100
  relevant_thresh: 3.5
  top_k: 5